/**
 * Client-side mock data for development
 * In production, this would be replaced with real API calls
 */

export const mockFinanceOverview = {
  stockMarketValue: {
    value: 150000,
    currency: "USD",
  },
  todayChange: {
    amount: 2500,
    percentage: 1.67,
  },
  totalUnrealizedGainLoss: {
    amount: 15000,
    percentage: 11.11,
  },
  ytdPercentage: 18.5,
  indices: [
    {
      symbol: "SPY",
      name: "S&P 500 ETF",
      value: 478.32,
      change: 1.25,
      changePercent: 0.26,
    },
    {
      symbol: "GOLD",
      name: "Gold",
      value: 2078.5,
      change: -5.3,
      changePercent: -0.25,
    },
    {
      symbol: "BTC",
      name: "Bitcoin",
      value: 42350.0,
      change: 850.0,
      changePercent: 2.05,
    },
    {
      symbol: "CA_JUMBO_ARM",
      name: "California Jumbo Loan 7/1 ARM",
      value: 6.875,
      change: -0.125,
      changePercent: -1.79,
    },
    {
      symbol: "POWERBALL",
      name: "Powerball Jackpot",
      value: 485000000,
      change: 0,
      changePercent: 0,
    },
  ],
  lastUpdated: new Date().toISOString(),
};

export const mockFinanceVideos = {
  videos: [
    {
      id: "abc123",
      title: "今日美股分析：科技股大涨原因解读",
      thumbnail: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=400&h=225&fit=crop",
      channel: "美股投资频道",
      publishedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
      url: "https://youtube.com/watch?v=abc123",
    },
    {
      id: "def456",
      title: "2025年投资策略：AI股票还能买吗？",
      thumbnail: "https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?w=400&h=225&fit=crop",
      channel: "财富自由之路",
      publishedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
      url: "https://youtube.com/watch?v=def456",
    },
    {
      id: "ghi789",
      title: "美联储最新利率决议解读",
      thumbnail: "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=400&h=225&fit=crop",
      channel: "经济观察",
      publishedAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
      url: "https://youtube.com/watch?v=ghi789",
    },
    {
      id: "jkl012",
      title: "科技股财报季预览",
      thumbnail: "https://images.unsplash.com/photo-1642790106117-e829e14a795f?w=400&h=225&fit=crop",
      channel: "投资观察",
      publishedAt: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
      url: "https://youtube.com/watch?v=jkl012",
    },
    {
      id: "mno345",
      title: "如何应对市场波动",
      thumbnail: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=225&fit=crop",
      channel: "理财专家",
      publishedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
      url: "https://youtube.com/watch?v=mno345",
    },
    {
      id: "pqr678",
      title: "2025年最值得关注的10只股票",
      thumbnail: "https://images.unsplash.com/photo-1563986768609-322da13575f3?w=400&h=225&fit=crop",
      channel: "股市分析师",
      publishedAt: new Date(Date.now() - 14 * 60 * 60 * 1000).toISOString(),
      url: "https://youtube.com/watch?v=pqr678",
    },
  ],
  lastUpdated: new Date().toISOString(),
};

export const mockBreakingNews = {
  news: [
    {
      id: "news001",
      title: "英伟达发布新一代AI芯片",
      summary_zh: "英伟达今日发布H200芯片，性能提升40%",
      why_it_matters_zh: "可能推动AI股票板块上涨，影响科技股投资决策",
      source: "Bloomberg",
      url: "https://bloomberg.com/",
      publishedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
      relevanceScore: 95,
    },
    {
      id: "news002",
      title: "特斯拉Q4财报超预期",
      summary_zh: "特斯拉第四季度交付量创历史新高",
      why_it_matters_zh: "电动车板块可能受提振，相关股票值得关注",
      source: "Reuters",
      url: "https://reuters.com/",
      publishedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
      relevanceScore: 88,
    },
    {
      id: "news003",
      title: "美联储维持利率不变",
      summary_zh: "联储决定暂不加息，观望经济数据",
      why_it_matters_zh: "利率稳定有利于科技股估值，房贷利率可能下降",
      source: "CNBC",
      url: "https://cnbc.com/",
      publishedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
      relevanceScore: 92,
    },
  ],
  lastUpdated: new Date().toISOString(),
};

export const mockIndustryNews = {
  news: [
    {
      id: "tech001",
      title: "OpenAI推出GPT-5预览版",
      summary_zh: "OpenAI向企业客户开放GPT-5早期访问",
      why_it_matters_zh: "可能影响AI工程师薪资水平和就业市场需求",
      tags: ["AI", "OpenAI", "就业"],
      source: "TechCrunch",
      url: "https://techcrunch.com/",
      publishedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
      relevanceScore: 92,
    },
    {
      id: "tech002",
      title: "谷歌云服务价格下调20%",
      summary_zh: "谷歌宣布大幅降低云计算服务价格",
      why_it_matters_zh: "云计算工程师需求可能增加，相关岗位薪资有望上涨",
      tags: ["云计算", "谷歌", "薪资"],
      source: "The Verge",
      url: "https://theverge.com/",
      publishedAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
      relevanceScore: 85,
    },
    {
      id: "tech003",
      title: "Meta开始新一轮招聘",
      summary_zh: "Meta计划在湾区招聘500名AI工程师",
      why_it_matters_zh: "就业市场转暖信号，求职者可关注相关机会",
      tags: ["招聘", "Meta", "AI"],
      source: "Bloomberg",
      url: "https://bloomberg.com/",
      publishedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
      relevanceScore: 90,
    },
    {
      id: "tech004",
      title: "苹果发布Vision Pro 2",
      summary_zh: "新一代VR头显性能翻倍，价格降低30%",
      why_it_matters_zh: "VR/AR领域工作机会可能增加",
      tags: ["苹果", "VR", "硬件"],
      source: "The Information",
      url: "https://theinformation.com/",
      publishedAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
      relevanceScore: 82,
    },
  ],
  lastUpdated: new Date().toISOString(),
};

export const mockIndustryVideos = {
  videos: [
    {
      id: "tech123",
      title: "本周科技新闻总结：AI行业大事件",
      thumbnail: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=400&h=225&fit=crop",
      channel: "科技速递",
      publishedAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
      url: "https://youtube.com/watch?v=tech123",
    },
    {
      id: "tech456",
      title: "湾区科技公司裁员与招聘动态",
      thumbnail: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=400&h=225&fit=crop",
      channel: "职场观察",
      publishedAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
      url: "https://youtube.com/watch?v=tech456",
    },
    {
      id: "tech789",
      title: "2025年最热门的编程语言和框架",
      thumbnail: "https://images.unsplash.com/photo-1542831371-29b0f74f9713?w=400&h=225&fit=crop",
      channel: "程序员成长",
      publishedAt: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
      url: "https://youtube.com/watch?v=tech789",
    },
    {
      id: "tech901",
      title: "硅谷最新薪资报告解读",
      thumbnail: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=225&fit=crop",
      channel: "职场分析",
      publishedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
      url: "https://youtube.com/watch?v=tech901",
    },
  ],
  lastUpdated: new Date().toISOString(),
};

export const mockChineseRestaurants = {
  restaurants: [
    {
      id: "rest001",
      name: "川味轩",
      rating: 4.6,
      reviewCount: 523,
      priceLevel: 2,
      cuisine: "Sichuan",
      address: "123 Main St, San Francisco, CA",
      distance: 2.3,
      photo: "https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=400&h=300&fit=crop",
      url: "https://www.google.com/maps/",
    },
    {
      id: "rest002",
      name: "北京烤鸭店",
      rating: 4.5,
      reviewCount: 412,
      priceLevel: 3,
      cuisine: "Beijing",
      address: "456 Market St, San Francisco, CA",
      distance: 3.1,
      photo: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=400&h=300&fit=crop",
      url: "https://www.google.com/maps/",
    },
    {
      id: "rest003",
      name: "上海小笼包",
      rating: 4.7,
      reviewCount: 689,
      priceLevel: 2,
      cuisine: "Shanghai",
      address: "789 Mission St, San Francisco, CA",
      distance: 1.8,
      photo: "https://images.unsplash.com/photo-1496116218417-1a781b1c416c?w=400&h=300&fit=crop",
      url: "https://www.google.com/maps/",
    },
    {
      id: "rest004",
      name: "广东茶餐厅",
      rating: 4.4,
      reviewCount: 356,
      priceLevel: 2,
      cuisine: "Cantonese",
      address: "321 Powell St, San Francisco, CA",
      distance: 2.7,
      photo: "https://images.unsplash.com/photo-1563245372-f21724e3856d?w=400&h=300&fit=crop",
      url: "https://www.google.com/maps/",
    },
  ],
  lastUpdated: new Date().toISOString(),
};

export const mockBubbleTeaShops = {
  shops: [
    {
      id: "shop001",
      name: "Happy Lemon",
      rating: 4.5,
      reviewCount: 312,
      priceLevel: 1,
      address: "456 Market St, San Francisco, CA",
      distance: 0.8,
      photo: "https://images.unsplash.com/photo-1525385133512-2f3bdd039054?w=400&h=300&fit=crop",
      url: "https://www.google.com/maps/",
    },
    {
      id: "shop002",
      name: "Boba Guys",
      rating: 4.6,
      reviewCount: 567,
      priceLevel: 2,
      address: "789 Valencia St, San Francisco, CA",
      distance: 1.2,
      photo: "https://images.unsplash.com/photo-1525385133512-2f3bdd039054?w=400&h=300&fit=crop",
      url: "https://www.google.com/maps/",
    },
    {
      id: "shop003",
      name: "Tiger Sugar",
      rating: 4.4,
      reviewCount: 423,
      priceLevel: 2,
      address: "234 Geary St, San Francisco, CA",
      distance: 0.5,
      photo: "https://images.unsplash.com/photo-1525385133512-2f3bdd039054?w=400&h=300&fit=crop",
      url: "https://www.google.com/maps/",
    },
    {
      id: "shop004",
      name: "Gong Cha",
      rating: 4.3,
      reviewCount: 289,
      priceLevel: 1,
      address: "567 Mission St, San Francisco, CA",
      distance: 1.5,
      photo: "https://images.unsplash.com/photo-1517487881594-2787fef5ebf7?w=400&h=300&fit=crop",
      url: "https://www.google.com/maps/",
    },
  ],
  lastUpdated: new Date().toISOString(),
};

export const mockShows = {
  shows: [
    {
      id: "show001",
      title: "繁花",
      description: "90年代上海商战故事",
      poster: "https://images.unsplash.com/photo-1598899134739-24c46f58b8c0?w=300&h=450&fit=crop",
      rating: 8.5,
      platform: "腾讯视频",
      url: "https://v.qq.com/",
    },
    {
      id: "show002",
      title: "三体",
      description: "刘慈欣科幻巨作改编",
      poster: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=300&h=450&fit=crop",
      rating: 8.2,
      platform: "腾讯视频",
      url: "https://v.qq.com/",
    },
    {
      id: "show003",
      title: "狂飙",
      description: "扫黑除恶题材剧集",
      poster: "https://images.unsplash.com/photo-1485846234645-a62644f84728?w=300&h=450&fit=crop",
      rating: 9.1,
      platform: "爱奇艺",
      url: "https://iqiyi.com/",
    },
  ],
  lastUpdated: new Date().toISOString(),
};

export const mockGossip = {
  posts: [
    {
      id: "gossip001",
      title: "湾区某大厂又裁员了",
      excerpt: "听说这次裁员规模不小，有人知道详情吗？",
      replyCount: 156,
      viewCount: 3420,
      url: "https://huaren.us/",
      publishedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
      hotScore: 88,
    },
    {
      id: "gossip002",
      title: "分享一个湾区买房的经历",
      excerpt: "终于在Fremont买到了心仪的房子...",
      replyCount: 89,
      viewCount: 2156,
      url: "https://huaren.us/",
      publishedAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
      hotScore: 75,
    },
    {
      id: "gossip003",
      title: "最近面试了几家公司的感受",
      excerpt: "市场确实在回暖，分享一下面试经验...",
      replyCount: 234,
      viewCount: 5678,
      url: "https://huaren.us/",
      publishedAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
      hotScore: 92,
    },
    {
      id: "gossip004",
      title: "湾区哪里的中餐最正宗？",
      excerpt: "想找一家好吃的川菜馆...",
      replyCount: 67,
      viewCount: 1234,
      url: "https://huaren.us/",
      publishedAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
      hotScore: 65,
    },
    {
      id: "gossip005",
      title: "孩子的中文教育问题",
      excerpt: "大家都是怎么教孩子中文的？",
      replyCount: 123,
      viewCount: 2890,
      url: "https://huaren.us/",
      publishedAt: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
      hotScore: 78,
    },
    {
      id: "gossip006",
      title: "Tesla还是Rivian？",
      excerpt: "纠结买哪个电动车...",
      replyCount: 45,
      viewCount: 987,
      url: "https://huaren.us/",
      publishedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
      hotScore: 58,
    },
    {
      id: "gossip007",
      title: "湾区最近治安怎么样？",
      excerpt: "感觉最近新闻里总是看到各种案件...",
      replyCount: 178,
      viewCount: 4321,
      url: "https://huaren.us/",
      publishedAt: new Date(Date.now() - 14 * 60 * 60 * 1000).toISOString(),
      hotScore: 85,
    },
    {
      id: "gossip008",
      title: "推荐几个湾区hiking的好地方",
      excerpt: "周末想去爬山，求推荐...",
      replyCount: 56,
      viewCount: 1456,
      url: "https://huaren.us/",
      publishedAt: new Date(Date.now() - 16 * 60 * 60 * 1000).toISOString(),
      hotScore: 62,
    },
    {
      id: "gossip009",
      title: "湾区华人超市大比拼",
      excerpt: "99大华、永和、Ranch 99哪家最好？",
      replyCount: 98,
      viewCount: 2234,
      url: "https://huaren.us/",
      publishedAt: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
      hotScore: 72,
    },
    {
      id: "gossip010",
      title: "说说你们的remote工作体验",
      excerpt: "全职remote快一年了，有点想回办公室...",
      replyCount: 145,
      viewCount: 3156,
      url: "https://huaren.us/",
      publishedAt: new Date(Date.now() - 20 * 60 * 60 * 1000).toISOString(),
      hotScore: 80,
    },
  ],
  lastUpdated: new Date().toISOString(),
};

export const mockDeals = {
  deals: [
    {
      id: "deal001",
      title: "Costco汽油优惠：每加仑便宜$0.30",
      description: "使用Costco信用卡额外返现4%",
      category: "gas",
      discountInfo: {
        type: "price_off",
        value: 0.3,
        unit: "per_gallon",
      },
      score: 92,
      practicalityScore: 38,
      discountScore: 24,
      timelinessScore: 18,
      popularityScore: 12,
      source: "huaren.us",
      sourceImage: "https://huaren.us/favicon.ico",
      url: "https://huaren.us/",
      expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
      publishedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "deal002",
      title: "Whole Foods Prime会员额外9折",
      description: "本周特价商品可叠加使用",
      category: "grocery",
      discountInfo: {
        type: "percentage",
        value: 10,
      },
      score: 88,
      practicalityScore: 36,
      discountScore: 22,
      timelinessScore: 18,
      popularityScore: 12,
      source: "huaren.us",
      sourceImage: "https://huaren.us/favicon.ico",
      url: "https://huaren.us/",
      expiresAt: new Date(Date.now() + 72 * 60 * 60 * 1000).toISOString(),
      publishedAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "deal003",
      title: "Uber Eats新用户首单免配送费",
      description: "满$20可用，最高省$5",
      category: "food_delivery",
      discountInfo: {
        type: "free_shipping",
        value: 5,
      },
      score: 85,
      practicalityScore: 34,
      discountScore: 21,
      timelinessScore: 18,
      popularityScore: 12,
      source: "huaren.us",
      sourceImage: "https://huaren.us/favicon.ico",
      url: "https://huaren.us/",
      expiresAt: new Date(Date.now() + 48 * 60 * 60 * 1000).toISOString(),
      publishedAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "deal004",
      title: "T-Mobile家庭套餐优惠",
      description: "4条线每月$120，无限流量",
      category: "mobile",
      discountInfo: {
        type: "bundle",
        value: 30,
      },
      score: 90,
      practicalityScore: 36,
      discountScore: 23,
      timelinessScore: 18,
      popularityScore: 13,
      source: "huaren.us",
      sourceImage: "https://huaren.us/favicon.ico",
      url: "https://huaren.us/",
      expiresAt: new Date(Date.now() + 168 * 60 * 60 * 1000).toISOString(),
      publishedAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "deal005",
      title: "Southwest航空促销：往返洛杉矶$99",
      description: "限时特价，需提前预订",
      category: "travel",
      discountInfo: {
        type: "special_price",
        value: 99,
      },
      score: 82,
      practicalityScore: 32,
      discountScore: 20,
      timelinessScore: 18,
      popularityScore: 12,
      source: "huaren.us",
      sourceImage: "https://huaren.us/favicon.ico",
      url: "https://huaren.us/",
      expiresAt: new Date(Date.now() + 96 * 60 * 60 * 1000).toISOString(),
      publishedAt: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "deal006",
      title: "Amazon Prime Day提前购",
      description: "电子产品最高5折",
      category: "electronics",
      discountInfo: {
        type: "percentage",
        value: 50,
      },
      score: 95,
      practicalityScore: 38,
      discountScore: 25,
      timelinessScore: 20,
      popularityScore: 12,
      source: "huaren.us",
      sourceImage: "https://huaren.us/favicon.ico",
      url: "https://huaren.us/",
      expiresAt: new Date(Date.now() + 120 * 60 * 60 * 1000).toISOString(),
      publishedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "deal007",
      title: "State Farm车险新客户优惠",
      description: "首年保费8折",
      category: "insurance",
      discountInfo: {
        type: "percentage",
        value: 20,
      },
      score: 87,
      practicalityScore: 35,
      discountScore: 22,
      timelinessScore: 18,
      popularityScore: 12,
      source: "huaren.us",
      sourceImage: "https://huaren.us/favicon.ico",
      url: "https://huaren.us/",
      expiresAt: new Date(Date.now() + 240 * 60 * 60 * 1000).toISOString(),
      publishedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "deal008",
      title: "Safeway会员专享：牛奶买一送一",
      description: "限Lucerne品牌",
      category: "grocery",
      discountInfo: {
        type: "bogo",
        value: 50,
      },
      score: 80,
      practicalityScore: 32,
      discountScore: 20,
      timelinessScore: 16,
      popularityScore: 12,
      source: "huaren.us",
      sourceImage: "https://huaren.us/favicon.ico",
      url: "https://huaren.us/",
      expiresAt: new Date(Date.now() + 48 * 60 * 60 * 1000).toISOString(),
      publishedAt: new Date(Date.now() - 14 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "deal009",
      title: "Comcast Xfinity宽带升级优惠",
      description: "升级到1Gbps只需$60/月",
      category: "internet",
      discountInfo: {
        type: "special_price",
        value: 60,
      },
      score: 89,
      practicalityScore: 36,
      discountScore: 22,
      timelinessScore: 18,
      popularityScore: 13,
      source: "huaren.us",
      sourceImage: "https://huaren.us/favicon.ico",
      url: "https://huaren.us/",
      expiresAt: new Date(Date.now() + 336 * 60 * 60 * 1000).toISOString(),
      publishedAt: new Date(Date.now() - 16 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "deal010",
      title: "Target Circle Week特惠",
      description: "全场额外8折，可叠加优惠券",
      category: "retail",
      discountInfo: {
        type: "percentage",
        value: 20,
      },
      score: 86,
      practicalityScore: 34,
      discountScore: 21,
      timelinessScore: 18,
      popularityScore: 13,
      source: "huaren.us",
      sourceImage: "https://huaren.us/favicon.ico",
      url: "https://huaren.us/",
      expiresAt: new Date(Date.now() + 72 * 60 * 60 * 1000).toISOString(),
      publishedAt: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "deal011",
      title: "Chipotle BOGO优惠",
      description: "使用app下单，买一送一",
      category: "food",
      discountInfo: {
        type: "bogo",
        value: 50,
      },
      score: 84,
      practicalityScore: 34,
      discountScore: 21,
      timelinessScore: 17,
      popularityScore: 12,
      source: "huaren.us",
      sourceImage: "https://huaren.us/favicon.ico",
      url: "https://huaren.us/",
      expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
      publishedAt: new Date(Date.now() - 20 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "deal012",
      title: "Best Buy会员日：笔记本电脑特价",
      description: "精选MacBook和ThinkPad最高省$300",
      category: "electronics",
      discountInfo: {
        type: "price_off",
        value: 300,
      },
      score: 91,
      practicalityScore: 36,
      discountScore: 23,
      timelinessScore: 19,
      popularityScore: 13,
      source: "huaren.us",
      sourceImage: "https://huaren.us/favicon.ico",
      url: "https://huaren.us/",
      expiresAt: new Date(Date.now() + 96 * 60 * 60 * 1000).toISOString(),
      publishedAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    },
  ],
  lastUpdated: new Date().toISOString(),
};
